name: unit-testing

on: [push, pull_request]

jobs:
  unit-test-academic-calendar-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd academic-calendar/react && yarn install && yarn run test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '18'
      - run: cd academic-calendar/react && yarn install && yarn run test:coverage
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: academic-calendar/react/coverage
